-- =====================================================================
-- Mimamori 初期スキーマ（企画書 §5）
--
-- 方針:
--   ・id は BIGINT GENERATED BY DEFAULT AS IDENTITY
--   ・日時は TIMESTAMPTZ。UTCで保存し、表示側で現地時間に直す
--   ・列挙値は VARCHAR + CHECK。DBのENUM型は値の追加が面倒なため使わない
--   ・削除は ON DELETE CASCADE。退会したら位置履歴も一緒に消える
-- =====================================================================

-- ---------------------------------------------------------------------
-- 認証・グループ
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(50)  NOT NULL,
    avatar_color  VARCHAR(7)   NOT NULL DEFAULT '#2F6BFF',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    invite_code VARCHAR(10) NOT NULL UNIQUE,
    created_by  BIGINT      NOT NULL REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE group_members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id       BIGINT      NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users (id)  ON DELETE CASCADE,
    role           VARCHAR(10) NOT NULL DEFAULT 'MEMBER',
    share_location BOOLEAN     NOT NULL DEFAULT TRUE,
    joined_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT group_members_role_check CHECK (role IN ('OWNER', 'MEMBER')),
    -- 同じ人が同じグループに二重に入れないようにする
    CONSTRAINT group_members_unique UNIQUE (group_id, user_id)
);

-- ---------------------------------------------------------------------
-- 位置と場所
-- ---------------------------------------------------------------------
CREATE TABLE locations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    lat           DOUBLE PRECISION NOT NULL,
    lng           DOUBLE PRECISION NOT NULL,
    accuracy      REAL,
    battery_level SMALLINT,
    address       VARCHAR(255),
    recorded_at   TIMESTAMPTZ      NOT NULL DEFAULT now()
);

-- 「その人の最新1件」を取る問い合わせが最も多い（企画書 §5）。
-- 降順の複合インデックスが無いと、履歴が増えるほど全件走査になる
CREATE INDEX locations_user_recorded_idx ON locations (user_id, recorded_at DESC);

CREATE TABLE places (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT           NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    name       VARCHAR(50)      NOT NULL,
    category   VARCHAR(10)      NOT NULL DEFAULT 'other',
    lat        DOUBLE PRECISION NOT NULL,
    lng        DOUBLE PRECISION NOT NULL,
    radius_m   INTEGER          NOT NULL,
    address    VARCHAR(255),
    enabled    BOOLEAN          NOT NULL DEFAULT TRUE,
    created_by BIGINT           NOT NULL REFERENCES users (id),
    created_at TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT places_category_check CHECK (category IN ('home', 'school', 'work', 'other')),
    -- GPS誤差で出入りを繰り返さない最小値（SC-P02 のスライダーと合わせる）
    CONSTRAINT places_radius_check CHECK (radius_m BETWEEN 50 AND 1000)
);

CREATE TABLE place_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT      NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users (id)  ON DELETE CASCADE,
    event_type  VARCHAR(10) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT place_events_type_check CHECK (event_type IN ('ARRIVE', 'LEAVE'))
);

CREATE INDEX place_events_occurred_idx ON place_events (occurred_at DESC);

-- ---------------------------------------------------------------------
-- SOS・呼び出し・通知
-- ---------------------------------------------------------------------
CREATE TABLE sos_alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT           NOT NULL REFERENCES users (id)  ON DELETE CASCADE,
    group_id     BIGINT           NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    lat          DOUBLE PRECISION NOT NULL,
    lng          DOUBLE PRECISION NOT NULL,
    status       VARCHAR(10)      NOT NULL DEFAULT 'ACTIVE',
    triggered_at TIMESTAMPTZ      NOT NULL DEFAULT now(),
    resolved_at  TIMESTAMPTZ,
    CONSTRAINT sos_alerts_status_check CHECK (status IN ('ACTIVE', 'RESOLVED'))
);

-- SC-S02 の「向かっています」。誰が向かっているか分からないと家族全員が
-- 同時に駆けつけてしまう（企画書 §2.3 と同じ考え方）
CREATE TABLE sos_responders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sos_alert_id BIGINT      NOT NULL REFERENCES sos_alerts (id) ON DELETE CASCADE,
    user_id      BIGINT      NOT NULL REFERENCES users (id)      ON DELETE CASCADE,
    responded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT sos_responders_unique UNIQUE (sos_alert_id, user_id)
);

CREATE TABLE pings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    to_user_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(15) NOT NULL DEFAULT 'SENT',
    sent_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at TIMESTAMPTZ,
    CONSTRAINT pings_status_check CHECK (status IN ('SENT', 'OK', 'LATER', 'NO_RESPONSE'))
);

CREATE INDEX pings_to_user_sent_idx ON pings (to_user_id, sent_at DESC);

-- 文章は保存しない。type と payload だけ持ち、表示は画面側で組み立てる
-- （企画書 §5 の注記。サーバーに日本語を埋めると後から直せなくなる）
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(20) NOT NULL,
    payload    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    is_read    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT notifications_type_check
        CHECK (type IN ('arrive', 'leave', 'battery', 'sos', 'ping_ok'))
);

-- 未読件数の取得（SC-N01 のベルのバッジ）を速くする
CREATE INDEX notifications_user_unread_idx
    ON notifications (user_id, created_at DESC)
    WHERE is_read = FALSE;

CREATE TABLE push_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    endpoint   TEXT         NOT NULL UNIQUE,
    p256dh     VARCHAR(255) NOT NULL,
    auth       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- トーク（F-15）
-- ---------------------------------------------------------------------
CREATE TABLE conversations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT      NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    type       VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT conversations_type_check CHECK (type IN ('GROUP', 'DIRECT'))
);

CREATE TABLE conversation_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    user_id         BIGINT      NOT NULL REFERENCES users (id)         ON DELETE CASCADE,
    -- 未読件数はこの時刻より後のメッセージを数えて出す
    last_read_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT conversation_members_unique UNIQUE (conversation_id, user_id)
);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    sender_id       BIGINT      NOT NULL REFERENCES users (id)         ON DELETE CASCADE,
    body            TEXT        NOT NULL,
    sent_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX messages_conversation_sent_idx ON messages (conversation_id, sent_at DESC);
