package com.mimamori.api.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

/**
 * 利用者（V1__init.sql の users）。
 *
 * <p>⚠️ クラス名 User に対しテーブル名は users。 USER は SQL の予約語なので単数形にはできない。
 */
@Entity
@Table(name = "users")
@Getter
@Setter
// JPA は引数なしコンストラクタを必要とする。
// protected にして、アプリのコードから空の User を作れないようにする
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class User {

    @Id
    // DB 側が BIGINT GENERATED BY DEFAULT AS IDENTITY なので IDENTITY を指定する
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /** BCrypt のハッシュ。平文は絶対に入れない */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(nullable = false, length = 50)
    private String name;

    /** アバターの背景色。#RRGGBB */
    @Column(name = "avatar_color", nullable = false, length = 7)
    private String avatarColor = "#2F6BFF";

    /** ⚠️ Instant を使う。LocalDateTime だとタイムゾーンを持たないため、 UTC で動く Railway と JST の開発機で9時間ずれる。 */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    public User(String email, String passwordHash, String name) {
        this.email = email;
        this.passwordHash = passwordHash;
        this.name = name;
    }
}
